name: CI

on:
  # Run on pushes targeting all branches
  push:
    branches: ["**"]

  # Run on pull request targeting master
  # pull_request:
  #   branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: "Setup Node"
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - name: "Install Dependencies"
        run: npm ci --include=dev
      - name: "Build"
        run: npm run build
      - name: "Check Code Format"
        run: npm run check-format
